[package]
name = "doom"
version = "0.1.0"
authors = ["diekmann <none@localhost>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
# Pure-Rust General MIDI synthesizer (SoundFont 2).  Compiles to
# wasm32-unknown-unknown out of the box.
rustysynth = "1.3"
